### ISSUE TITLE
question about fullcalendar.make

### ISSUE THREAD

**Issue by Lowell20** [dakala/fullcalendar#2]
is this obsolete or are you using it.
it is referencing fullcalendar-1.6.0
which version are we working with? 
it looks like the current version is 2.7.3

**Comment by dakala** [comment]
It needs to be updated to the current version which is 2.7.3. That's what I think we should be targeting bearing in mind the warning on the project page on d.o. (https://www.drupal.org/project/fullcalendar):

"WARNING: The module has only been tested with the 1.5.x version of the jQuery plugin. The 2.0.x version has shown some issues, consider using the older versions."

**Comment by Lowell20** [comment]
it looks like we are using jquery 2.1.4, right?

**Comment by dakala** [comment]
Yes, that's correct. If you look in my fullcalendar.services.yml you'll notice that I'm not using their version of jquery for now. The core/jquery dependency takes care of it. If we get the calendar displaying and discover we need their version, that shouldn't be a problem.

**Comment by Lowell20** [comment]
Yes, it is good to have a baseline understanding. We are now looking at the same versions.
